# Generated by Django 5.1 on 2024-08-30 21:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalImageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(default='Unknown Device', max_length=100)),
                ('average_before_normalization', models.FloatField(default=0.0)),
                ('average_after_normalization', models.FloatField(default=0.0)),
                ('data_size', models.IntegerField(default=0)),
                ('raw_data', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
